# Generated by Django 3.1.3 on 2020-11-11 18:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201111_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 18, 57, 47, 285432, tzinfo=utc)),
        ),
    ]
